### ISSUE TITLE
Key error when running the code

### ISSUE THREAD

**Issue by AdarshMJ** [BenGutteridge/DRew#2]
Hi, I am unable to run the code. I keep getting this error -

```
Traceback (most recent call last):
  File "/usr/local0/Adarsh/DRew-main/lrgb/main.py", line 104, in <module>
    load_cfg(cfg, args)
  File "/home/rml/.local/lib/python3.10/site-packages/torch_geometric/graphgym/config.py", line 500, in load_cfg
    cfg.merge_from_file(args.cfg_file)
  File "/home/rml/.local/lib/python3.10/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/rml/.local/lib/python3.10/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/rml/.local/lib/python3.10/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/rml/.local/lib/python3.10/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: train.mode'
```

Im not sure how to fix this. Any suggestions would be helpful.

**Comment by AdarshMJ** [comment]
I also keep getting this error -

```python
Traceback (most recent call last):
  File "/usr/local0/Adarsh/DRew-main/lrgb/main.py", line 141, in <module>
    optimizer = create_optimizer(model.parameters(),cfg)
  File "/home/rml/.local/lib/python3.10/site-packages/torch_geometric/graphgym/optim.py", line 38, in create_optimizer
    return from_config(func)(params, cfg=cfg)
  File "/home/rml/.local/lib/python3.10/site-packages/torch_geometric/graphgym/config.py", line 582, in wrapper
    raise ValueError(f"'cfg.{arg_name}' undefined")
ValueError: 'cfg.optimizer_config' undefined
```
I have followed the instructions on running the code but it has too many errors.

**Comment by BenGutteridge** [comment]
I think this is a torch (and possibly pyg) version issue
